version: "3.8"

services:
  calcom-api:
    image: jhonatancreeai/calcom:latest
    container_name: calcom-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - API_URL=https://minhaagenda.creeai.com.br
      - DATABASE_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - DATABASE_DIRECT_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - BOOKING_ROUTE=/booking
      - EVENT_TYPE_ROUTE=/event-types
      - USER_ROUTE=/user
      - HEALTH_ROUTE=/health
      - ROOT_ROUTE=/
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
