version: "3.8"

services:
  calcom-api:
    image: jhonatancreeai/calcom:latest
    container_name: calcom-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - API_URL=https://minhaagenda.creeai.com.br
      - DATABASE_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - DATABASE_DIRECT_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - BOOKING_ROUTE=/booking
      - EVENT_TYPE_ROUTE=/event-types
      - USER_ROUTE=/user
      - HEALTH_ROUTE=/health
      - ROOT_ROUTE=/
    networks:
      - calcom-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: calcom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - calcom-network
    depends_on:
      - calcom-api
    restart: unless-stopped

networks:
  calcom-network:
    driver: bridge
