version: "3.7"

services:
  calcom-api:
    image: jhonatancreeai/calcom:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - network_swarm_public
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - API_URL=https://minhaagenda.creeai.com.br
      - DATABASE_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - DATABASE_DIRECT_URL=postgres://postgres:bd1b2ca145206fd646ce@painel.creeai.com.br:5433/cal?sslmode=disable
      - BOOKING_ROUTE=/booking
      - EVENT_TYPE_ROUTE=/event-types
      - USER_ROUTE=/user
      - HEALTH_ROUTE=/health
      - ROOT_ROUTE=/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.calcom-api.rule=Host(`minhaagenda.creeai.com.br`)
        - traefik.http.routers.calcom-api.entrypoints=web
        - traefik.http.routers.calcom-api.service=calcom-api
        - traefik.http.services.calcom-api.loadbalancer.server.port=3000
        - traefik.http.services.calcom-api.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.calcom-api-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
        - traefik.http.middlewares.calcom-api-cors.headers.accesscontrolallowheaders=Origin,X-Requested-With,Content-Type,Accept,Authorization
        - traefik.http.middlewares.calcom-api-cors.headers.accesscontrolalloworiginlist=*
        - traefik.http.routers.calcom-api.middlewares=calcom-api-cors

networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
